### ISSUE TITLE
wiringPi Segmentation Fault

### ISSUE THREAD

**Issue by Dan-escu** [Dan-escu/ONDA#3]
When attempting to display the fundamental frequency on the LCD display, the main code completes 9 cycles and a segmentation fault occurs after these. This issue occurs every time data is being displayed on the LCD panel using lcdPrintf or lcdPuts.

**Comment by niallmarshall** [comment]
There was an issue with initialising wiringPi setup each time inside a loop, resulting in the maximum number of 'new LCD's' set by wiring pi. Fixed by moving the wiringPi setup outside the loop so it intialises once.
